version: "3.8"
services:
  mysql:
    image: landscapedatacommons/swhub-test-mysql:8.0.32
    build:
      context: ./mysql
      args:
        DOCKER_BUILDKIT: 1
    deploy:
      restart_policy:
        condition: on-failure
        max-attempts: 3
    restart: on-failure
    security_opt:
      - seccomp:unconfined
    command: --default_authentication-plugin=mysql_native_password
    networks:
      - test-net
    expose: 
      - 3306
    volumes:
      - /opt/docker/swhub-test/src/mysql:/docker-entrypoint-initdb.d
      - test-mysql-data:/var/lib/mysql

  drupal-test:
    image: landscapedatacommons/swhub-drupal:9.5.3-php8.1-apache
    build:
      context: /opt/docker/swhub-test
      dockerfile: drupal/Dockerfile
    depends_on:
      - mysql
    networks:
      - test-net
      - public
    volumes:
      - test-drupal:/opt/drupal
      - test-drupal-data:/var/www/html
      - /opt/docker/swhub-test/src/mysql:/var/mysql/backups
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.swhub-test.service=swhub-test"
        - "traefik.http.routers.swhub-test.entrypoints=websecure"
        - "traefik.http.services.swhub-test.loadbalancer.server.port=80"
        - "traefik.http.routers.swhub-test.rule=Host( `swhub-test.nmsu.edu` )"
        - "traefik.http.routers.swhub-test.tls.certresolver=leresolver"

  composer:
    image: composer:2.5.4
    depends_on:
      - drupal-test
    working_dir: /opt/drupal
    command: ["sh", "update-composer.sh"]
    networks:
      - test-net
    volumes:
      - test-drupal:/opt/drupal

networks:
  public:
    external: true
  test-net:
    external: true

volumes:
  test-drupal:
    external: true
  test-drupal-data:
    external: true
  test-mysql-data:
    external: true